In [1]:
import numpy as np

# 创建数组
numpy.array(object,dtype=None,**kw)

In [2]:
np.array([[1,2],[2,3],[3,4]])

array([[1, 2],
       [2, 3],
       [3, 4]])

# 数据属性
$ndim$      -  返回int。表示数组的维度

$shape$     -  返回tuple。表示数组的尺寸，对于n行m列的矩阵，形状为（n，m）

$size$      -  返回int。表示数组的元素总数，等于数组形状的乘积

$dtype$     -  返回data-type。描述数组中元素的类型

$itemsize$  -  返回int。表示数组的每个元素的大小

# 数据类型
$bool$ - 用一位储存的布尔类型

$inti$ - 由所在平台决定其精度的整数

$int8$ - 整数，范围为-128至127

$int16$ - 整数，范围为-32768至32767

$int32$ - 整数，范围为-2^31至2^32-1

$float16$ - 半精度浮点数

# 等差数列和等比数列
等差数列：
- $arange（start，end，step）$可接受浮点数
- $linspace（start，stop，num=50，endpoint=True）$

等比数列：
- $logspace（start，stop，num=50，endpoint=True，base=10）$

In [3]:
a = np.arange(10,30,2)
b = np.arange(0,5,0.5)
c = np.linspace(0,100,num=20)
d = np.logspace(0,100,num=20)
a,b,c,d

(array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28]),
 array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5]),
 array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
         21.05263158,  26.31578947,  31.57894737,  36.84210526,
         42.10526316,  47.36842105,  52.63157895,  57.89473684,
         63.15789474,  68.42105263,  73.68421053,  78.94736842,
         84.21052632,  89.47368421,  94.73684211, 100.        ]),
 array([1.00000000e+000, 1.83298071e+005, 3.35981829e+010, 6.15848211e+015,
        1.12883789e+021, 2.06913808e+026, 3.79269019e+031, 6.95192796e+036,
        1.27427499e+042, 2.33572147e+047, 4.28133240e+052, 7.84759970e+057,
        1.43844989e+063, 2.63665090e+068, 4.83293024e+073, 8.85866790e+078,
        1.62377674e+084, 2.97635144e+089, 5.45559478e+094, 1.00000000e+100]))

# 修改数组维度
numpy.reshape(arr, newshape, order='C')

$order$：'C' -- 按行，'F' -- 按列，'A' -- 原顺序，'k' -- 元素在内存中的出现顺序。

In [4]:
print(np.reshape(a,(2,5)))
print(b.reshape((2,5)))

[[10 12 14 16 18]
 [20 22 24 26 28]]
[[0.  0.5 1.  1.5 2. ]
 [2.5 3.  3.5 4.  4.5]]


# 转换数据类型
array.astype(dtype)

In [5]:
a.astype(float)

array([10., 12., 14., 16., 18., 20., 22., 24., 26., 28.])

# 创建特定数组
numpy.zeros(shape, dtype=float, order='C')

numpy.ones(shape, dtype=None, order='C') 

numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C') - 创建对角线上是1，其他是0的数组

numpy.diag(v, k=0) - 创建对角线上为指定数字,其他是0的数组

In [6]:
print(np.zeros((3,4)))
print(np.ones((3,2)))
print(np.eye((3)))
print(np.diag([1,2,3,4]))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


# 生成随机数
- numpy.random.random(size=None) *参数是整数或元组，生成[0.0,1.0)之间的随机浮点数*

- numpy.random.rand(d0, d1, ..., dn) *生成一个N维的数组，元素取自[0,1)上的均匀分布的随机数*

- numpy.random.randint(low, high=None, size=None, dtype=int) *从[low,high)中随机采样，生成随机整数*

- numpy.random.randint(low=0.0, high=1.0, size=None) *从[low,high)中随机采样，生成随机浮点数*

- numpy.random.normal(loc=0.0, scale=1.0, size=None) *生成符合正态分布的数组*

In [7]:
print('1:',np.random.random((3,2,2)))
print('2:',np.random.rand(2,3,2))
print('3:',np.random.randint(0,100,size=(2,5)))
print('4:',np.random.uniform(0,100,size=(2,5)))
print('5:',np.random.normal(1.5,3,(3,4))) #均值为1.5，标准差为3，3行4列

1: [[[0.3114211  0.00463427]
  [0.56763211 0.97995489]]

 [[0.49208049 0.15643257]
  [0.31723853 0.63275037]]

 [[0.06886849 0.72541405]
  [0.10578742 0.12173262]]]
2: [[[0.37335033 0.39484615]
  [0.9339159  0.94179052]
  [0.98472742 0.67161938]]

 [[0.74909754 0.7729498 ]
  [0.78803056 0.75771078]
  [0.28097346 0.0173869 ]]]
3: [[87 28 73 13 37]
 [48 91 54 73 64]]
4: [[48.77108535 21.83721187 81.4133086  71.20578014 84.61914901]
 [65.39104031 19.63592543 66.47572706  7.82726946 85.03100835]]
5: [[ 4.50723486 -1.41489812  4.56588815 -0.04851249]
 [ 2.12456553  2.47886748  3.24358536 -0.9908554 ]
 [-0.60084614  3.28130524 -1.21144842  1.17926643]]


# 数组运算
$四则运算$ - 形状必须相同 - 加减乘除幂

$比较运算$ - 返回布尔数组

$逻辑运算$ - np.any表示逻辑“or”，np.all表示逻辑“and”，返回布尔值

In [9]:
print(a+b)
print(a>b)
print(a.all())

[10.  12.5 15.  17.5 20.  22.5 25.  27.5 30.  32.5]
[ True  True  True  True  True  True  True  True  True  True]


TypeError: only integer scalar arrays can be converted to a scalar index