In [1]:
#索引 start:end:step end为开区间
import numpy as np

In [3]:
b = np.array([[1,2,3],[2,3,4]])

In [4]:
print(b)

[[1 2 3]
 [2 3 4]]


In [7]:
b.ndim
b.shape
#长宽，几行几列
b.dtype
#datatype 数据类型

dtype('int64')

In [14]:
c = np.arange(0,25,2.5)
#range 只能取整数；arange 可整可浮
print(c)

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]


In [11]:
d = np.linspace(0,100,20)
print(d)
#range 和 linspace 默认生成一维数组

[  0.           5.26315789  10.52631579  15.78947368  21.05263158
  26.31578947  31.57894737  36.84210526  42.10526316  47.36842105
  52.63157895  57.89473684  63.15789474  68.42105263  73.68421053
  78.94736842  84.21052632  89.47368421  94.73684211 100.        ]


In [19]:
e = c.reshape(5,2)
#reshape 函数可以修改数组维度

array([[ 0. ,  2.5],
       [ 5. ,  7.5],
       [10. , 12.5],
       [15. , 17.5],
       [20. , 22.5]])

In [20]:
print(b.astype(float))
#astype 可以更改数据类型

[[1. 2. 3.]
 [2. 3. 4.]]


In [23]:
f = np.logspace(1,10,num = 20,base = 2)
print(f)

[   2.            2.77730229    3.85670399    5.3556164     7.43708284
   10.32751358   14.34131354   19.91508143   27.65510059   38.40328703
   53.32876841   74.05505519  102.836637    142.80421347  198.30523421
  275.37679007  382.40229418  531.02338276  737.40622722 1024.        ]
