In [4]:
import numpy as np

In [7]:
b = np.array([[1,2,5],[3,4,6],[7,8,8]])
b

array([[1, 2, 5],
       [3, 4, 6],
       [7, 8, 8]])

In [15]:
b[[0,2],1:]

array([[2, 5],
       [8, 8]])

In [17]:
b>3

array([[False, False,  True],
       [False,  True,  True],
       [ True,  True,  True]])

In [18]:
b[b>3] #非常重要

array([5, 4, 6, 7, 8, 8])

In [22]:
# numpy中没有and，or，not；要使用&，｜，~
b[(b % 2 == 0) & (b > 3)]

array([4, 6, 8, 8])

In [24]:
# where 函数类似if语句
# where(condition,if True, if False)
np.where(b>3,b-1,b)

array([[1, 2, 4],
       [3, 3, 5],
       [6, 7, 7]])

In [28]:
np.piecewise(b,[b<3,(b>3) & (b<5),b>5],[-1,1,lambda x: x*4])

array([[-1, -1,  0],
       [ 0,  1, 24],
       [28, 32, 32]])

In [30]:
a = np.array([1,7,3,6,2])
a.sort()# sort 为原位操作函数，得到的结果仍然在原来的位置
print(a)

[1 2 3 6 7]
