In [4]:
import numpy as np

In [7]:
b = np.array([[1,2,5],[3,4,6],[7,8,8]])
b

array([[1, 2, 5],
       [3, 4, 6],
       [7, 8, 8]])

In [15]:
b[[0,2],1:]

array([[2, 5],
       [8, 8]])

In [17]:
b>3

array([[False, False,  True],
       [False,  True,  True],
       [ True,  True,  True]])

In [18]:
b[b>3] #非常重要

array([5, 4, 6, 7, 8, 8])

In [22]:
# numpy中没有and，or，not；要使用&，｜，~
b[(b % 2 == 0) & (b > 3)]

array([4, 6, 8, 8])

In [24]:
# where 函数类似if语句
# where(condition,if True, if False)
np.where(b>3,b-1,b)

array([[1, 2, 4],
       [3, 3, 5],
       [6, 7, 7]])

In [28]:
np.piecewise(b,[b<3,(b>3) & (b<5),b>5],[-1,1,lambda x: x*4])

array([[-1, -1,  0],
       [ 0,  1, 24],
       [28, 32, 32]])

In [30]:
a = np.array([1,7,3,6,2])
a.sort()# sort 为原位操作函数，得到的结果仍然在原来的位置
print(a)

[1 2 3 6 7]


In [13]:
import numpy as np
length = np.loadtxt('/Users/hukeer/Downloads/iris_sepal_length.csv',delimiter = ',')
length.sort()
length

array([4.3, 4.4, 4.4, 4.4, 4.5, 4.6, 4.6, 4.6, 4.6, 4.7, 4.7, 4.8, 4.8,
       4.8, 4.8, 4.8, 4.9, 4.9, 4.9, 4.9, 4.9, 4.9, 5. , 5. , 5. , 5. ,
       5. , 5. , 5. , 5. , 5. , 5. , 5.1, 5.1, 5.1, 5.1, 5.1, 5.1, 5.1,
       5.1, 5.1, 5.2, 5.2, 5.2, 5.2, 5.3, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4,
       5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.6, 5.6, 5.6, 5.6, 5.6, 5.6,
       5.7, 5.7, 5.7, 5.7, 5.7, 5.7, 5.7, 5.7, 5.8, 5.8, 5.8, 5.8, 5.8,
       5.8, 5.8, 5.9, 5.9, 5.9, 6. , 6. , 6. , 6. , 6. , 6. , 6.1, 6.1,
       6.1, 6.1, 6.1, 6.1, 6.2, 6.2, 6.2, 6.2, 6.3, 6.3, 6.3, 6.3, 6.3,
       6.3, 6.3, 6.3, 6.3, 6.4, 6.4, 6.4, 6.4, 6.4, 6.4, 6.4, 6.5, 6.5,
       6.5, 6.5, 6.5, 6.6, 6.6, 6.7, 6.7, 6.7, 6.7, 6.7, 6.7, 6.7, 6.7,
       6.8, 6.8, 6.8, 6.9, 6.9, 6.9, 6.9, 7. , 7.1, 7.2, 7.2, 7.2, 7.3,
       7.4, 7.6, 7.7, 7.7, 7.7, 7.7, 7.9])

In [14]:
print(np.unique(length))

[4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9 6.
 6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1 7.2 7.3 7.4 7.6 7.7 7.9]


In [15]:
print(np.sum(length))

876.5


In [16]:
print(np.cumsum(length))

[  4.3   8.7  13.1  17.5  22.   26.6  31.2  35.8  40.4  45.1  49.8  54.6
  59.4  64.2  69.   73.8  78.7  83.6  88.5  93.4  98.3 103.2 108.2 113.2
 118.2 123.2 128.2 133.2 138.2 143.2 148.2 153.2 158.3 163.4 168.5 173.6
 178.7 183.8 188.9 194.  199.1 204.3 209.5 214.7 219.9 225.2 230.6 236.
 241.4 246.8 252.2 257.6 263.1 268.6 274.1 279.6 285.1 290.6 296.1 301.7
 307.3 312.9 318.5 324.1 329.7 335.4 341.1 346.8 352.5 358.2 363.9 369.6
 375.3 381.1 386.9 392.7 398.5 404.3 410.1 415.9 421.8 427.7 433.6 439.6
 445.6 451.6 457.6 463.6 469.6 475.7 481.8 487.9 494.  500.1 506.2 512.4
 518.6 524.8 531.  537.3 543.6 549.9 556.2 562.5 568.8 575.1 581.4 587.7
 594.1 600.5 606.9 613.3 619.7 626.1 632.5 639.  645.5 652.  658.5 665.
 671.6 678.2 684.9 691.6 698.3 705.  711.7 718.4 725.1 731.8 738.6 745.4
 752.2 759.1 766.  772.9 779.8 786.8 793.9 801.1 808.3 815.5 822.8 830.2
 837.8 845.5 853.2 860.9 868.6 876.5]


In [17]:
print(np.mean(length))

5.843333333333334


In [18]:
print(np.std(length))

0.8253012917851409


In [19]:
print(np.var(length))

0.6811222222222223


In [22]:
print(np.min(length))

4.3


In [21]:
print(np.max(length))

7.9


In [24]:
length[(length % 2 == 0) & (length > 4)]

array([6., 6., 6., 6., 6., 6.])

In [26]:
print(np.where(length > 4, 1, -1))

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1]


In [33]:
alcoholic = np.random.randint(0,2,2000)
alcoholic = np.where(alcoholic == 0, -1, 1)
distance = np.cumsum(alcoholic)
step = np.argmax(alcoholic)
if step >= 15:
    print(step)
else:
    print("酒鬼最远也没走到15米")

酒鬼最远也没走到15米
